"""Build the checked-in corpus manifest from an explicit source catalogue."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "corpus_v2" / "manifest.json"
REVIEW_DATE = "2026-09-06"


def _sha256(path: Path, media_type: str) -> str:
    content = path.read_bytes()
    if media_type in {"text/markdown", "text/html"}:
        text = content.decode("utf-8-sig")
        content = text.replace("\r\n", "\n").replace("\r", "\n").encode()
    return hashlib.sha256(content).hexdigest()


def _source(
    source_id: str,
    relative_path: str,
    *,
    title: str | None = None,
    document_version: str | None = None,
    media_type: str = "text/markdown",
    source_kind: str,
    use: str,
    jurisdiction: str,
    topics: tuple[str, ...],
    normative_tier: str,
    synthetic: bool,
    certification_level: str,
    official_source_urls: tuple[str, ...] = (),
    approved_locators: tuple[str, ...] = (),
    reason_codes: tuple[str, ...] = (),
    published_on: str | None = None,
    effective_from: str | None = None,
    effective_to: str | None = None,
    reviewed_on: str | None = None,
    supersedes: tuple[str, ...] = (),
) -> dict[str, Any]:
    path = ROOT / relative_path
    return {
        "source_id": source_id,
        "title": title,
        "document_version": document_version,
        "relative_path": relative_path,
        "content_sha256": _sha256(path, media_type),
        "media_type": media_type,
        "source_kind": source_kind,
        "use": use,
        "jurisdiction": jurisdiction,
        "topics": list(topics),
        "normative_tier": normative_tier,
        "synthetic": synthetic,
        "certification_level": certification_level,
        "official_source_urls": list(official_source_urls),
        "approved_locators": list(approved_locators),
        "reason_codes": list(reason_codes),
        "published_on": published_on,
        "effective_from": effective_from,
        "effective_to": effective_to,
        "reviewed_on": reviewed_on,
        "supersedes": list(supersedes),
    }


def _official(
    source_id: str,
    relative_path: str,
    title: str,
    version: str,
    jurisdiction: str,
    topics: tuple[str, ...],
    source_kind: str,
    urls: tuple[str, ...],
    published_on: str,
    effective_from: str,
    *,
    media_type: str = "text/markdown",
    approved_locators: tuple[str, ...],
) -> dict[str, Any]:
    return _source(
        source_id,
        relative_path,
        title=title,
        document_version=version,
        media_type=media_type,
        source_kind=source_kind,
        use="SERVING",
        jurisdiction=jurisdiction,
        topics=topics,
        normative_tier="STATUTORY",
        synthetic=False,
        certification_level="PRIMARY_SOURCE_CHECKED",
        official_source_urls=urls,
        approved_locators=approved_locators,
        published_on=published_on,
        effective_from=effective_from,
        reviewed_on=REVIEW_DATE,
    )


def _policy(
    source_id: str,
    relative_path: str,
    title: str,
    version: str,
    jurisdiction: str,
    topics: tuple[str, ...],
    published_on: str,
    effective_from: str,
    *,
    source_kind: str = "COMPANY_POLICY",
    effective_to: str | None = None,
    supersedes: tuple[str, ...] = (),
) -> dict[str, Any]:
    return _source(
        source_id,
        relative_path,
        title=title,
        document_version=version,
        source_kind=source_kind,
        use="SERVING",
        jurisdiction=jurisdiction,
        topics=topics,
        normative_tier="COMPANY_POLICY",
        synthetic=True,
        certification_level="DEMO_POLICY_REVIEWED",
        published_on=published_on,
        effective_from=effective_from,
        effective_to=effective_to,
        reviewed_on=REVIEW_DATE,
        supersedes=supersedes,
    )


def _fixture(source_id: str, filename: str, topics: tuple[str, ...], reason: str) -> dict[str, Any]:
    return _source(
        source_id,
        f"corpus_v2/fixtures/adversarial/{filename}",
        source_kind="TEST_FIXTURE",
        use="ADVERSARIAL_TEST",
        jurisdiction="TEST",
        topics=topics,
        normative_tier="COMPANY_POLICY",
        synthetic=True,
        certification_level="NOT_REVIEWED",
        reason_codes=("SERVING_EXCLUSION_TEST", reason),
    )


def _legacy(
    source_id: str,
    relative_path: str,
    jurisdiction: str,
    topics: tuple[str, ...],
    normative_tier: str,
    use: str,
    reasons: tuple[str, ...],
) -> dict[str, Any]:
    return _source(
        source_id,
        relative_path,
        source_kind="LEGACY",
        use=use,
        jurisdiction=jurisdiction,
        topics=topics,
        normative_tier=normative_tier,
        synthetic=normative_tier == "COMPANY_POLICY",
        certification_level="NOT_REVIEWED",
        reason_codes=reasons,
    )


def build_manifest() -> dict[str, Any]:
    all_topics = ("gratuity", "notice", "leave")
    coss_url = "https://www.labour.gov.in/static/uploads/2025/07/b0620548445580767b5c0d18c95c26f7.pdf"
    wages_url = "https://www.labour.gov.in/static/uploads/2025/06/c328da14bbb15fc4ad571dc33e7a4ab3.pdf"
    faq_url = "https://www.labour.gov.in/static/uploads/2026/03/a4ccf4c6d97c4f1f36a6d83f8c64213d.pdf"
    uae_law_url = "https://uaelegislation.gov.ae/en/legislations/1541"

    sources = [
        _official(
            "in-coss-2020-raw",
            "corpus_v2/raw/india/code_social_security_2020.pdf",
            "Code on Social Security, 2020",
            "Act 36 of 2020",
            "India",
            ("gratuity",),
            "PRIMARY_LAW",
            (coss_url,),
            "2020-09-29",
            "2025-11-21",
            media_type="application/pdf",
            approved_locators=("Section 2(88)", "Sections 53-56"),
        ),
        _official(
            "in-wages-2019-raw",
            "corpus_v2/raw/india/code_wages_2019.pdf",
            "Code on Wages, 2019",
            "Act 29 of 2019",
            "India",
            ("gratuity",),
            "PRIMARY_LAW",
            (wages_url,),
            "2019-08-08",
            "2025-11-21",
            media_type="application/pdf",
            approved_locators=("Section 2(y)",),
        ),
        _official(
            "in-labour-codes-faq-2026-03-16-raw",
            "corpus_v2/raw/india/labour_codes_faq_2026-03-16.pdf",
            "Additional FAQs on Labour Codes",
            "2026-03-16",
            "India",
            ("gratuity",),
            "OFFICIAL_GUIDANCE",
            (faq_url,),
            "2026-03-16",
            "2026-03-16",
            media_type="application/pdf",
            approved_locators=("Questions 6-7, 13-14, 16-17, and 19",),
        ),
        _official(
            "in-labour-codes-employer-handbook-2026-raw",
            "corpus_v2/raw/india/labour_codes_employer_handbook_2026.pdf",
            "Compliance Handbook for Employers Under the Four Labour Codes",
            "2026.1",
            "India",
            all_topics,
            "OFFICIAL_GUIDANCE",
            ("https://www.labour.gov.in/static/uploads/2026/02/83978455025732b99b0165def80ab171.pdf",),
            "2026-02-18",
            "2026-02-18",
            media_type="application/pdf",
            approved_locators=("Chapters 2-5",),
        ),
        _official(
            "in-labour-codes-commencement-scope",
            "corpus_v2/sources/india/labour_codes_commencement_scope.md",
            "India labour-code commencement reviewed scope note",
            "2026-09-06",
            "India",
            all_topics,
            "REVIEWED_EXTRACT",
            (
                "https://egazette.gov.in/WriteReadData/2025/267882.pdf",
                "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2192463",
            ),
            "2026-09-06",
            "2025-11-21",
            approved_locators=("Certified statements",),
        ),
        _official(
            "in-annual-leave-scope",
            "corpus_v2/sources/india/annual_leave_scope.md",
            "India annual leave reviewed statutory scope note",
            "2026-09-06",
            "India",
            ("leave",),
            "REVIEWED_EXTRACT",
            (
                "https://www.labour.gov.in/whatsnew/occupational-safety-health-and-working-conditions-code-2020-no-37-2020",
                "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2192802",
            ),
            "2026-09-06",
            "2025-11-21",
            approved_locators=("Certified demo rule",),
        ),
        _official(
            "in-notice-scope",
            "corpus_v2/sources/india/notice_scope.md",
            "India employment notice reviewed statutory scope note",
            "2026-09-06",
            "India",
            ("notice",),
            "REVIEWED_EXTRACT",
            (
                "https://www.labour.gov.in/offerings/schemes-and-services/details/labour-codes-gzNzQzMtQWa",
                "https://www.labour.gov.in/static/uploads/2026/02/83978455025732b99b0165def80ab171.pdf",
            ),
            "2026-09-06",
            "2025-11-21",
            approved_locators=("Certified demo behaviour",),
        ),
        _official(
            "ae-labour-law-end-of-service-extract",
            "corpus_v2/sources/uae/federal_law_end_of_service.md",
            "UAE mainland end-of-service reviewed statutory extract",
            "2026-09-06",
            "UAE",
            ("gratuity",),
            "REVIEWED_EXTRACT",
            (uae_law_url,),
            "2021-09-20",
            "2022-02-02",
            approved_locators=("Article 51",),
        ),
        _official(
            "ae-labour-law-notice-extract",
            "corpus_v2/sources/uae/federal_law_notice.md",
            "UAE mainland notice reviewed statutory extract",
            "2026-09-06",
            "UAE",
            ("notice",),
            "REVIEWED_EXTRACT",
            (uae_law_url,),
            "2021-09-20",
            "2022-02-02",
            approved_locators=("Articles 9 and 43",),
        ),
        _official(
            "ae-labour-law-leave-extract",
            "corpus_v2/sources/uae/federal_law_annual_leave.md",
            "UAE mainland annual leave reviewed statutory extract",
            "2026-09-06",
            "UAE",
            ("leave",),
            "REVIEWED_EXTRACT",
            (uae_law_url,),
            "2021-09-20",
            "2022-02-02",
            approved_locators=("Article 29",),
        ),
        _official(
            "ae-executive-regulation-scope",
            "corpus_v2/sources/uae/executive_regulation_scope.md",
            "UAE labour executive regulation reviewed scope note",
            "2026-09-06",
            "UAE",
            all_topics,
            "REVIEWED_EXTRACT",
            (
                "https://uaelegislation.gov.ae/en/legislations/1547",
                "https://mohre.gov.ae/assets/download/2617404c/Cabinet%20Resolution%20_Executive%20Regulations%20Decree-Law%20No.%2033.pdf.aspx",
            ),
            "2022-02-03",
            "2022-02-02",
            approved_locators=("Certified demo behaviour",),
        ),
        _policy(
            "meridian-global-policy-hierarchy-2023",
            "corpus_v2/sources/global/policy_hierarchy_2023.md",
            "Meridian policy authority and hierarchy",
            "2023.1",
            "GLOBAL",
            all_topics,
            "2022-12-01",
            "2023-01-01",
            effective_to="2025-01-01",
        ),
        _policy(
            "meridian-global-policy-hierarchy-v1",
            "corpus_v2/sources/global/policy_hierarchy.md",
            "Meridian policy authority and hierarchy",
            "1.0",
            "GLOBAL",
            all_topics,
            "2024-12-01",
            "2025-01-01",
            supersedes=("meridian-global-policy-hierarchy-2023",),
        ),
        _policy(
            "meridian-global-facts-records-v1",
            "corpus_v2/sources/global/employee_facts_and_records.md",
            "Meridian employee facts and source records",
            "1.0",
            "GLOBAL",
            all_topics,
            "2024-12-01",
            "2025-01-01",
            source_kind="COMPANY_PROCEDURE",
        ),
        _policy(
            "meridian-global-answering-guide-v1",
            "corpus_v2/sources/global/hr_answering_guide.md",
            "Meridian HR policy answering guide",
            "1.0",
            "GLOBAL",
            all_topics,
            "2024-12-01",
            "2025-01-01",
            source_kind="COMPANY_PROCEDURE",
        ),
        _policy(
            "meridian-india-gratuity-policy-2023",
            "corpus_v2/sources/india/gratuity_policy_2023.md",
            "Meridian India gratuity policy",
            "2023.1",
            "India",
            ("gratuity",),
            "2022-12-01",
            "2023-01-01",
            effective_to="2025-11-21",
        ),
        _policy(
            "meridian-india-gratuity-policy-2025",
            "corpus_v2/sources/india/meridian_gratuity_policy.md",
            "Meridian India gratuity policy",
            "2025.1",
            "India",
            ("gratuity",),
            "2025-11-21",
            "2025-11-21",
            supersedes=("meridian-india-gratuity-policy-2023",),
        ),
        _policy(
            "meridian-india-notice-policy-2023",
            "corpus_v2/sources/india/notice_policy_2023.md",
            "Meridian India notice policy",
            "2023.1",
            "India",
            ("notice",),
            "2022-12-01",
            "2023-01-01",
            effective_to="2025-07-01",
        ),
        _policy(
            "meridian-india-notice-policy-2025",
            "corpus_v2/sources/india/notice_policy_2025.md",
            "Meridian India notice policy",
            "2025.1",
            "India",
            ("notice",),
            "2025-06-01",
            "2025-07-01",
            supersedes=("meridian-india-notice-policy-2023",),
        ),
        _policy(
            "meridian-india-leave-policy-2023",
            "corpus_v2/sources/india/leave_policy_2023.md",
            "Meridian India leave policy",
            "2023.1",
            "India",
            ("leave",),
            "2022-12-01",
            "2023-01-01",
            effective_to="2024-07-01",
        ),
        _policy(
            "meridian-india-leave-policy-2024",
            "corpus_v2/sources/india/leave_policy_2024.md",
            "Meridian India leave policy",
            "2024.2",
            "India",
            ("leave",),
            "2024-06-01",
            "2024-07-01",
            supersedes=("meridian-india-leave-policy-2023",),
        ),
        _policy(
            "meridian-india-policy-faq-2026",
            "corpus_v2/sources/india/employee_policy_faq.md",
            "Meridian India employee policy FAQ",
            "2026.1",
            "India",
            all_topics,
            "2026-04-01",
            "2026-04-01",
            source_kind="COMPANY_FAQ",
        ),
        _policy(
            "meridian-india-payroll-gratuity-procedure-2023",
            "corpus_v2/sources/india/payroll_gratuity_procedure_2023.md",
            "Meridian India payroll gratuity procedure",
            "2023.1",
            "India",
            ("gratuity",),
            "2022-12-01",
            "2023-01-01",
            source_kind="COMPANY_PROCEDURE",
            effective_to="2026-04-01",
        ),
        _policy(
            "meridian-india-payroll-gratuity-procedure-2026",
            "corpus_v2/sources/india/payroll_gratuity_procedure.md",
            "Meridian India payroll gratuity procedure",
            "2026.1",
            "India",
            ("gratuity",),
            "2026-04-01",
            "2026-04-01",
            source_kind="COMPANY_PROCEDURE",
            supersedes=("meridian-india-payroll-gratuity-procedure-2023",),
        ),
        _policy(
            "meridian-uae-mainland-scope-v1",
            "corpus_v2/sources/uae/mainland_scope_handbook.md",
            "Meridian UAE mainland handbook scope",
            "1.0",
            "UAE",
            all_topics,
            "2022-01-15",
            "2022-02-02",
        ),
        _policy(
            "meridian-uae-eos-policy-2022",
            "corpus_v2/sources/uae/end_of_service_policy_2022.md",
            "Meridian UAE mainland end-of-service policy",
            "2022.1",
            "UAE",
            ("gratuity",),
            "2022-01-15",
            "2022-02-02",
            effective_to="2025-01-01",
        ),
        _policy(
            "meridian-uae-eos-policy-2025",
            "corpus_v2/sources/uae/end_of_service_policy_2025.md",
            "Meridian UAE mainland end-of-service policy",
            "2025.1",
            "UAE",
            ("gratuity",),
            "2024-11-15",
            "2025-01-01",
            supersedes=("meridian-uae-eos-policy-2022",),
        ),
        _policy(
            "meridian-uae-notice-policy-2022",
            "corpus_v2/sources/uae/notice_policy_2022.md",
            "Meridian UAE mainland notice policy",
            "2022.1",
            "UAE",
            ("notice",),
            "2022-01-15",
            "2022-02-02",
            effective_to="2026-08-01",
        ),
        _policy(
            "meridian-uae-notice-policy-2026",
            "corpus_v2/sources/uae/notice_policy_2026.md",
            "Meridian UAE mainland notice policy",
            "2026.2",
            "UAE",
            ("notice",),
            "2026-07-01",
            "2026-08-01",
            supersedes=("meridian-uae-notice-policy-2022",),
        ),
        _policy(
            "meridian-uae-leave-policy-2022",
            "corpus_v2/sources/uae/annual_leave_policy_2022.md",
            "Meridian UAE mainland annual leave policy",
            "2022.1",
            "UAE",
            ("leave",),
            "2022-01-15",
            "2022-02-02",
            effective_to="2025-06-01",
        ),
        _policy(
            "meridian-uae-leave-policy-2025",
            "corpus_v2/sources/uae/annual_leave_policy_2025.md",
            "Meridian UAE mainland annual leave policy",
            "2025.1",
            "UAE",
            ("leave",),
            "2025-05-01",
            "2025-06-01",
            supersedes=("meridian-uae-leave-policy-2022",),
        ),
        _policy(
            "meridian-uae-policy-faq-2026",
            "corpus_v2/sources/uae/employee_policy_faq.md",
            "Meridian UAE mainland employee policy FAQ",
            "2026.1",
            "UAE",
            all_topics,
            "2026-04-01",
            "2026-04-01",
            source_kind="COMPANY_FAQ",
        ),
        _policy(
            "meridian-uae-payroll-eos-procedure-2026",
            "corpus_v2/sources/uae/payroll_end_of_service_procedure.md",
            "Meridian UAE mainland payroll end-of-service procedure",
            "2026.1",
            "UAE",
            ("gratuity",),
            "2026-04-01",
            "2026-04-01",
            source_kind="COMPANY_PROCEDURE",
        ),
        _fixture(
            "fixture-false-four-year-gratuity-threshold",
            "false_four_year_threshold.md",
            ("gratuity",),
            "INTENTIONALLY_FALSE",
        ),
        _fixture("fixture-document-prompt-injection", "document_prompt_injection.md", all_topics, "PROMPT_INJECTION"),
        _fixture("fixture-fabricated-uae-notice", "fabricated_uae_notice.md", ("notice",), "FABRICATED_LAW"),
        _fixture(
            "fixture-future-india-leave-amendment",
            "future_india_leave_amendment.md",
            ("leave",),
            "FUTURE_DATED",
        ),
        _fixture("fixture-unsigned-policy-override", "unsigned_policy_override.md", ("notice",), "UNAPPROVED"),
        _fixture("fixture-wrong-jurisdiction-leave", "wrong_jurisdiction_leave.md", ("leave",), "WRONG_JURISDICTION"),
        _fixture("fixture-duplicate-policy-copy", "duplicate_policy_copy.md", all_topics, "DUPLICATE"),
        _fixture("fixture-missing-effective-date", "missing_effective_date.md", ("gratuity",), "DATE_UNRESOLVED"),
        _fixture("fixture-superseded-marked-current", "superseded_marked_current.md", ("leave",), "FALSE_STATUS"),
        _fixture(
            "fixture-gross-salary-as-basic-wage", "gross_salary_as_basic_wage.md", ("gratuity",), "WRONG_WAGE_BASIS"
        ),
        _legacy(
            "legacy-india-law-v1",
            "corpus/tier1_law/india/india_law.md",
            "India",
            ("gratuity", "notice", "leave"),
            "STATUTORY",
            "QUARANTINED",
            (
                "OUTDATED_AFTER_LABOUR_CODES_COMMENCEMENT",
                "FALSE_FOUR_YEAR_GRATUITY_THRESHOLD",
                "NON_AUTHORITATIVE_SOURCE_CITATIONS",
            ),
        ),
        _legacy(
            "legacy-uae-mainland-law-v1",
            "corpus/tier1_law/uae/uae_law.md",
            "UAE",
            all_topics,
            "STATUTORY",
            "DEFERRED",
            ("REPLACED_BY_REVIEWED_SCOPED_EXTRACTS", "RAW_OFFICIAL_ARTIFACT_PENDING"),
        ),
        _legacy(
            "legacy-difc-law-v1",
            "corpus/tier1_law/uae/uae_difc_law.md",
            "UAE-DIFC",
            all_topics,
            "STATUTORY",
            "DEFERRED",
            ("OUTSIDE_ACTIVE_PORTFOLIO_SCOPE", "INCORRECT_VACATION_CARRY_FORWARD_SUMMARY"),
        ),
        _legacy(
            "legacy-germany-law-v1",
            "corpus/tier1_law/germany/germany_law.md",
            "Germany",
            all_topics,
            "STATUTORY",
            "DEFERRED",
            ("COUNTRY_DEFERRED_FROM_PORTFOLIO_SCOPE", "NON_PRIMARY_SOURCE_CITATION"),
        ),
        _legacy(
            "legacy-meridian-global-policy-v1",
            "corpus/tier2_policy/meridian_global_preamble.md",
            "GLOBAL",
            all_topics,
            "COMPANY_POLICY",
            "QUARANTINED",
            ("MIXED_ADVERSARIAL_FIXTURE", "INCOMPLETE_GOVERNING_LAW_RULE"),
        ),
        _legacy(
            "legacy-meridian-india-policy-v1",
            "corpus/tier2_policy/india/meridian_india_policy.md",
            "India",
            all_topics,
            "COMPANY_POLICY",
            "QUARANTINED",
            ("MIXED_ADVERSARIAL_FIXTURES", "REFERENCES_QUARANTINED_STATUTORY_BASELINE"),
        ),
        _legacy(
            "legacy-meridian-uae-policy-v1",
            "corpus/tier2_policy/uae/meridian_uae_policy.md",
            "UAE",
            all_topics,
            "COMPANY_POLICY",
            "QUARANTINED",
            ("MIXED_ADVERSARIAL_FIXTURES", "REPLACED_BY_CLEAN_V2_POLICY_SET"),
        ),
        _legacy(
            "legacy-meridian-germany-policy-v1",
            "corpus/tier2_policy/germany/meridian_germany_policy.md",
            "Germany",
            all_topics,
            "COMPANY_POLICY",
            "DEFERRED",
            ("COUNTRY_DEFERRED_FROM_PORTFOLIO_SCOPE", "MIXED_ADVERSARIAL_FIXTURES"),
        ),
        _source(
            "in-coss-2020-gratuity-demo-extract-v1",
            "corpus_v2/sources/india/gratuity_statutory_extract.md",
            source_kind="REVIEWED_EXTRACT",
            use="DEFERRED",
            jurisdiction="India",
            topics=("gratuity",),
            normative_tier="STATUTORY",
            synthetic=False,
            certification_level="PRIMARY_SOURCE_CHECKED",
            official_source_urls=(coss_url, faq_url),
            reason_codes=("REPLACED_BY_RAW_PRIMARY_SOURCE_SET",),
        ),
    ]
    return {
        "schema_version": 2,
        "corpus_generation": "india-uae-policy-portfolio-2026-09-06-v1",
        "as_of_date": REVIEW_DATE,
        "active_jurisdictions": ["GLOBAL", "India", "UAE"],
        "active_topics": list(all_topics),
        "production_legal_reviewed": False,
        "inventory_roots": ["corpus", "corpus_v2/raw", "corpus_v2/sources", "corpus_v2/fixtures"],
        "sources": sources,
    }


def render_manifest() -> str:
    return json.dumps(build_manifest(), indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_manifest()
    if args.check:
        return 0 if MANIFEST_PATH.read_text(encoding="utf-8") == rendered else 1
    MANIFEST_PATH.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
